services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Register all services in the bundle
    SymfonyDDD\CoreBundle\:
        resource: '../src/'
        exclude:
            - '../src/CoreBundle.php'
            - '../src/DependencyInjection/'
            - '../src/ValueObject/'
            - '../src/Exception/'
